title: Zaid Qureshi

# deployment only
baseurl: "/zaid"
url: "https://dontcallmebigguy.github.io"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
