title: Zaid Qureshi
url: "/"
baseurl: "https://dontcallmebigguy.github.io/zaid"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
